[package]
name = "lower-macros"
version = "0.2.13"
authors = ["bend-n <bend.n@outlook.com>"]
description = "desugar math where the compiler wont"
edition = "2024"
repository = "https://git.bendn.org/lower"
license = "MIT"

[dependencies]
proc-macro2 = "1.0.107"
quote = "1.0.47"
syn = { version = "3.0.5", features = ["full"] }

[lib]
proc-macro = true
